# Generated by Django 3.1.4 on 2021-01-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='born_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
