# Generated by Django 3.1.4 on 2021-01-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0002_auto_20210103_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='born_on',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
