# Generated by Django 3.1.4 on 2021-01-03 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0003_auto_20210103_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baby',
            options={'verbose_name_plural': 'Babies'},
        ),
        migrations.AddField(
            model_name='baby',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='baby',
            name='secret_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
