# Generated by Django 3.1.4 on 2021-03-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0004_auto_20210103_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='extra',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
