# Generated by Django 3.1.4 on 2021-06-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0005_baby_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='announce_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
